name: passwd
description: A beautiful and secure password manager.
version: 1.0.0+1
author: Akshit Garg

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  archive: ^2.0.13
  auto_route: ^0.6.7
  barcode_scan: ^3.0.1
  base_x: ^1.0.1
  cached_network_image: ^2.2.0+1
  crypto: ^2.1.5
  cryptography: ^1.4.1
  dart_otp: ^1.3.0
  dio: ^3.0.10
  encrypt: ^4.0.2
  ez_localization: ^0.3.0+1
  flutter_hooks: ^0.13.1
  flutter_icons: ^1.1.0
  flutter_otp_text_field: ^0.0.1+1
  flutter_secure_storage: ^3.3.3
  get_it: ^4.0.4
  google_fonts: ^1.1.0
  injectable: ^1.0.4
  local_auth: ^0.6.2+3
  msgpack_dart: ^0.0.7
  path: ^1.7.0
  path_provider: ^1.6.11
  percent_indicator: ^2.1.5
  responsive_builder: ^0.3.0
  shared_preferences: ^0.5.10
  stacked: ^1.7.6
  stacked_services: ^0.5.2
  supercharged: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.7.5
  injectable_generator: ^1.0.4
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/languages/

flutter_icons:
  android: true
  ios: true
  image_path_ios: assets/icons/ios.png
  adaptive_icon_background: assets/icons/adaptive_bg.png
  adaptive_icon_foreground: assets/icons/adaptive_fg.png
  image_path_android: assets/icons/android.png
